### PR TITLE
City beautification

### PR DESCRIPTION
**Pull request by dadobug1111**
returned grass (and all other biome blocks) to the cities

fixed near ocean underground chunk errors as a byproduct

made rubble generate moss/mossy cobble/mossy bricks instead of stone

It is not perfect, but I think it is much better than stone cities

### CODE REVIEW

**Comment by McJty** [comment]
I'll check it out soon. Thanks

**Comment by McJty** [comment]
Why this?

            if (profile.isDefault()) {
                clearToMax(info, heightmap, height);
            }
            //if (profile.isDefault()) {
                //clearToMax(info, heightmap, height);
            //}

I don't think this should be disabled. Removing this can cause ugly floating bits of terrain

**Comment by dadobug1111** [comment]
because it clears the grass from the sides of the paths 
also the terrain adjustment usually only done around the cities (like in mountains) is now applied in city chunks, squishing any floating terrain down
```
        //city surface leveling - for prettier cities
        //note: Better results may be achieved with terrain noise adjustment (like how newer structures do it)
        int ground = info.getCityGroundLevel();
        for (int x = 0; x < 16; x++) {
            for (int z = 0; z < 16; z++) {
                boolean moved = moveDown(x, z, ground + 1, info.waterLevel > info.groundLevel);

                if (!moved) {
                    moveUp(x, z, ground, info.waterLevel > info.groundLevel);
                }
            }
        }
```

**Comment by McJty** [comment]
Ok but that should only be done when profile.isDefault() is true. That's missing a test

**Comment by McJty** [comment]
I merged because I want to try it out locally. It may be that I still change some of this

**Comment by McJty** [comment]
Ok, there is a problem:

image

Lots of patches of floating grass. This was not there before

**Comment by McJty** [comment]
Seems that grass is generating at the height where the terrain used to generate before the city flattened it?

**Comment by McJty** [comment]
Bringing back this code fixes it:

            if (profile.isDefault()) {
                clearToMax(info, heightmap, height);
            }

Not sure if that can have other consenquences or if there is a better way to fix this?

**Comment by McJty** [comment]
I think the problem is that in moveDown you do this:

        while (isFoliageOrEmpty(driver.getBlock()) && driver.getY() > height) {
            driver.decY();
        }

That means that the grass on top of the hills will not be moved down as far as I understand your code right

**Comment by dadobug1111** [comment]
well yes, but it also stops trees at chunk borders from doing bad things

this also seems to fix it
```
        if (profile.isDefault()) {
            clearToMax(info, heightmap, height+1);
        }
```

**Comment by McJty** [comment]
Maybe this is a better fix:

In moveDown:

        while (isEmpty(driver.getBlock()) && driver.getY() > height) {
            driver.decY();
        }

i.e. use isEmpty instead of isEmptyOrFoliage. At least that fixes it for me

**Comment by dadobug1111** [comment]
this happens - trees do funny things at chunk borders

**Comment by McJty** [comment]
yes but the grass problem  is way uglier

**Comment by McJty** [comment]
I did commit my fix so far. Maybe you can have a look to see if you can find a better fix for this. Would be nice if we can avoid the clearToMax as that eats a bit of performance

**Comment by dadobug1111** [comment]
optimally we would use noise adjustment, but I have not figured out quite how that works yet - looking into it though!

**Comment by McJty** [comment]
I'm going to replace the list of materials and the random dirt with tags. Tags are a much better system to use for this. That way it can easily be configured too

**Comment by McJty** [comment]
BTW, this is really inefficient:

Arrays.stream(randomDirt).anyMatch((b) -> b == leafBaseState

Basically randomDirt is an array of 128 items that only contains three possible blocks: mossy stone bricks, cobblestone and moss block. So you are first making a stream of these 128 items (slow already, object creation) and then iterating over it (not all 128 entries as it stops at first match, but still).

Going to replace this with a simple Set.contains

**Pull request merged**
