### PR TITLE
- Minor fixes and addon.

### PR DESCRIPTION
**Pull request by TqLxQuanZ**
- Fixed bridge doesn't generate with local palette.
- Added options for generating doors, dungeon rails and underground filler for more customization to devs. (As some custom building doesn't need the filler nor doors)

### CODE REVIEW

**Comment by McJty** [comment]
Thanks. I'll check this out soon

**Comment by TqLxQuanZ** [comment]
> Thanks. I'll check this out soon

@McJty Any idea when this can be added? I have a modpack that requires the changes.

**Comment by Nick1st** [comment]
I'd move the door and filler option to the building instead of to the whole profile.

**Comment by strubium** [comment]
> Thanks. I'll check this out soon

I beg of ye, please add this.

**Comment by McJty** [comment]
I no longer work on the 1.16 version. I would consider this for the 1.18/1.19 version though

**Comment by strubium** [comment]
> I no longer work on the 1.16 version. I would consider this for the 1.18/1.19 version though

1.12.2?

**Comment by McJty** [comment]
That's even older. Only 1.18 or better

**Comment by strubium** [comment]
BETTER?

**Comment by McJty** [comment]
Yes?

**Comment by strubium** [comment]
i _will_ throw a temper tantrum because 1.12.2 is the most stable for mods

**Comment by McJty** [comment]
My mods are all a lot better on more modern versions of Minecraft and also perform better. In addition you're really missing out on a lot of the new features in vanilla. Especially the increased world height. Also internally the vanilla code has improved a huge deal. So not sure where you got it from that 1.12.2 is most stable. It most certainly isn't

**Comment by strubium** [comment]
> My mods are all a lot better on more modern versions of Minecraft and also perform better. In addition you're really missing out on a lot of the new features in vanilla. Especially the increased world height. Also internally the vanilla code has improved a huge deal. So not sure where you got it from that 1.12.2 is most stable. It most certainly isn't       

Hmmm,  increased world height seems like it would add some cool stuff to this mod, and having to deal with less Minecraft spaghetti would speed up the dev process. 

I understand giving up on older versions, but this was a perfectly good pull request that fixed a bug and added features (by the way, on the most common for most Minecraft versions for modders, followed by 1.12.2 and 1.7.10 AND you even left the 1.16 branch as the default branch) 

It pisses me off that you gave up on "older"  versions but won't let your community take over support.

**Comment by McJty** [comment]
Problem is that I no longer have a setup for releasing 1.12 or 1.16 mods. That requires Java 8 and I no longer have that on my computer. Releasing a mod is a lot of work and I'm already struggling to maintain my 1.18 and later versions. I really can't do it

**Comment by strubium** [comment]
Yeah, that's completely fine. But again this pull request would help you maintain your slightly older versions. Are there special steps for releasing a patch that requires Java 8? Do you need/want help from your community?

**Pull request closed without merging**
