### PR TITLE
Upgrade Gradle

### PR DESCRIPTION
**Pull request by Windmill-City**
Upgrade Forge Version
Upgrade Dependencies version
Remove unused items

### CODE REVIEW

**Comment by dtorgy** [comment]
@Windmill-City have you tested dying in the lost city dimension after the forge upgrade? 
I believe this forge bugfix broke lost cities dimension re-spawning: https://github.com/MinecraftForge/MinecraftForge/pull/4982
Forge version: 14.23.4.2753

java.util.concurrent.ExecutionException: java.lang.NoSuchFieldError: managedPosX
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_261]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_261]
	at net.minecraft.util.Util.runTask(SourceFile:47) [Util.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
Caused by: java.lang.NoSuchFieldError: managedPosX
	at net.minecraft.entity.player.EntityPlayerMP.copyFrom(EntityPlayerMP.java:1170) ~[EntityPlayerMP.class:?]
	at net.minecraft.server.management.PlayerList.recreatePlayerEntity(PlayerList.java:540) ~[PlayerList.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processClientStatus(NetHandlerPlayServer.java:1117) ~[NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.CPacketClientStatus.processPacket(SourceFile:31) ~[CPacketClientStatus.class:?]
	at net.minecraft.network.play.client.CPacketClientStatus.processPacket(SourceFile:8) ~[CPacketClientStatus.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_261]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_261]
	at net.minecraft.util.Util.runTask(SourceFile:46) ~[Util.class:?]

**Comment by dtorgy** [comment]
I can consistently trigger this when doing a runClient or starting MC from the IDE. When I launch MC normally, I can not reproduce. Soooo I think that this must be a only me thing.

**Comment by Windmill-City** [comment]
> I can consistently trigger this when doing a runClient or starting MC from the IDE. When I launch MC normally, I can not reproduce. Soooo I think that this must be a only me thing.

Sorry, I am not working on this anymore

**Comment by Windmill-City** [comment]
> I can consistently trigger this when doing a runClient or starting MC from the IDE. When I launch MC normally, I can not reproduce. Soooo I think that this must be a only me thing.

this may help -> https://github.com/Nick1st/LCPatches

**Comment by McJty** [comment]
Sorry but I no longer support 1.12

**Pull request closed without merging**
